DDP_CONFIG:
  WORLD_SIZE: 1
  WORLD_RANK: 0
  GPU_WORLD_SIZE: 8
  GPU_WORLD_RANK: 0
  DIST_URL: 'tcp://163.152.29.64:23457'
  WOLRD_URLS: ['163.152.29.64']
  AUTO_RANK_MATCH: True
  DIST_BACKEND: 'nccl'
  GPU: 0
  DISTRIBUTED: True

CONFIG:
  VISIBLE_GPU: 0,1,2,3,4,5,6,7

  TRAIN:
    EPOCH_NUM: 50
    BATCH_SIZE: 90
    LR: 0.005
    MOMENTUM: 0.9
    W_DECAY: 1e-4
    LR_POLICY: 'Step'
    USE_WARMUP: False
    LR_MILESTONE: [20, 30, 40]
    STEP: 0.1

  VAL:
    FREQ: 1
    BATCH_SIZE: 50

  ADV:
    METHOD: 'FGSM'
    TYPE: 'Random'
    FRAME: 8

  DATA:
    DATASET: 'ucf'
    TRAIN_ANNO_PATH: '../../data/video/UCF101/ucfTrainTestlist/newtrainlist01.txt'
    VAL_ANNO_PATH: '../../data/video/UCF101/ucfTrainTestlist/newtestlist01.txt'
    DATA_PATH: '../../data/video/UCF101/original_videos'
    CLASS_IDX_PATH: '../../data/video/UCF101/ucfTrainTestlist/classInd.txt'
    NUM_CLASSES: 101
    CLIP_LEN: 32
    FRAME_RATE: 2
    NUM_SEGMENT: 1
    NUM_CROP: 1
    TEST_NUM_SEGMENT: 10
    TEST_NUM_CROP: 3
    MULTIGRID: False
    KEEP_ASPECT_RATIO: False

  MODEL:
    NAME: 'i3d_resnet50_v1_custom'
    PRETRAINED: True
    LOAD: True
    LOAD_PATH: 'models/i3d_ucf.pth'

  LOG:
    BASE_PATH: './logs/i3d'
    LOG_DIR: 'tb_log'
    SAVE_DIR: 'checkpoints'
    EVAL_DIR: './logs/i3d/eval'
    SAVE_FREQ: 1