DDP_CONFIG:
  WORLD_SIZE: 1
  WORLD_RANK: 0
  GPU_WORLD_SIZE: 8
  GPU_WORLD_RANK: 0
  DIST_URL: 'tcp://163.152.29.65:23456'
  WOLRD_URLS: ['163.152.29.65']
  AUTO_RANK_MATCH: True
  DIST_BACKEND: 'nccl'
  GPU: 0
  DISTRIBUTED: True

CONFIG:
  VISIBLE_GPU: 0,1,2,3

  TRAIN:
    EPOCH_NUM: 100
    BATCH_SIZE: 50
    LR: 0.05
    MOMENTUM: 0.9
    W_DECAY: 1e-4
    LR_POLICY: 'Step'
    USE_WARMUP: False
    WARMUP_EPOCHS: 5
    WARMUP_END_LR: 0.05
    LR_MILESTONE: [10, 30, 50]
    STEP: 0.1

  VAL:
    FREQ: 1
    BATCH_SIZE: 80

  DATA:
    TRAIN_ANNO_PATH: '../../../../hub_data/video/ucfTrainTestlist/trainlist01.txt'
    VAL_ANNO_PATH: '../../../../hub_data/video/ucfTrainTestlist/testlist01_new.txt'
    DATA_PATH: '../../../../hub_data/video/ucf101'
    CLASS_IDX_PATH: '../../../../hub_data/video/ucfTrainTestlist/classInd.txt'
    NUM_CLASSES: 101
    CLIP_LEN: 32
    FRAME_RATE: 2
    NUM_SEGMENT: 1
    NUM_CROP: 1
    TEST_NUM_SEGMENT: 10
    TEST_NUM_CROP: 3
    MULTIGRID: False
    KEEP_ASPECT_RATIO: False

  MODEL:
    NAME: 'r3d_18'
    PRETRAINED: False
    LOAD: False
    LOAD_PATH: 'logs/r3d/r3d_baseline.pth'

  LOG:
    BASE_PATH: './logs/r3d'
    LOG_DIR: 'tb_log'
    SAVE_DIR: 'checkpoints'
    EVAL_DIR: './logs/r3d/eval'
    SAVE_FREQ: 1