# python adversarial_attack.py --config-file=config_i3d.yaml
# python adversarial_attack.py --config-file=./config/i3d/config_i3d_1.yaml
# python adversarial_attack.py --config-file=./config/i3d/config_i3d_2.yaml
# python adversarial_attack.py --config-file=./config/i3d/config_i3d_3.yaml
# python adversarial_attack.py --config-file=./config/i3d/config_i3d_4.yaml
# python adversarial_attack.py --config-file=./config/i3d/config_i3d_5.yaml
# python adversarial_attack.py --config-file=./config/i3d/config_i3d_6.yaml
# python adversarial_attack.py --config-file=./config/i3d/config_i3d_7.yaml
# python adversarial_attack.py --config-file=./config/i3d/config_i3d_8.yaml
# python adversarial_attack.py --config-file=./config/i3d/config_i3d_9.yaml
# python adversarial_attack.py --config-file=./config/i3d/config_i3d_10.yaml
# python adversarial_attack.py --config-file=./config/i3d/config_i3d_11.yaml
# python adversarial_attack.py --config-file=./config/i3d/config_i3d_12.yaml

# python adversarial_attack.py --config-file=config_r3d.yaml
# python adversarial_attack.py --config-file=./config/r3d/config_r3d_1.yaml
# python adversarial_attack.py --config-file=./config/r3d/config_r3d_2.yaml
# python adversarial_attack.py --config-file=./config/r3d/config_r3d_3.yaml
# python adversarial_attack.py --config-file=./config/r3d/config_r3d_4.yaml
# python adversarial_attack.py --config-file=./config/r3d/config_r3d_5.yaml
# python adversarial_attack.py --config-file=./config/r3d/config_r3d_6.yaml
# python adversarial_attack.py --config-file=./config/r3d/config_r3d_7.yaml
# python adversarial_attack.py --config-file=./config/r3d/config_r3d_8.yaml
# python adversarial_attack.py --config-file=./config/r3d/config_r3d_9.yaml
# python adversarial_attack.py --config-file=./config/r3d/config_r3d_10.yaml
# python adversarial_attack.py --config-file=./config/r3d/config_r3d_11.yaml
# python adversarial_attack.py --config-file=./config/r3d/config_r3d_12.yaml

# python adversarial_attack.py --config-file=config_r2plus1d.yaml
# python adversarial_attack.py --config-file=./config/r2plus1d/config_r2plus1d_1.yaml
# python adversarial_attack.py --config-file=./config/r2plus1d/config_r2plus1d_2.yaml
# python adversarial_attack.py --config-file=./config/r2plus1d/config_r2plus1d_3.yaml
# python adversarial_attack.py --config-file=./config/r2plus1d/config_r2plus1d_4.yaml
# python adversarial_attack.py --config-file=./config/r2plus1d/config_r2plus1d_5.yaml
# python adversarial_attack.py --config-file=./config/r2plus1d/config_r2plus1d_6.yaml
# python adversarial_attack.py --config-file=./config/r2plus1d/config_r2plus1d_7.yaml
# python adversarial_attack.py --config-file=./config/r2plus1d/config_r2plus1d_8.yaml
# python adversarial_attack.py --config-file=./config/r2plus1d/config_r2plus1d_9.yaml
# python adversarial_attack.py --config-file=./config/r2plus1d/config_r2plus1d_10.yaml
# python adversarial_attack.py --config-file=./config/r2plus1d/config_r2plus1d_11.yaml
# python adversarial_attack.py --config-file=./config/r2plus1d/config_r2plus1d_12.yaml

python adversarial_attack.py --config-file=config_lrcn.yaml 
python adversarial_attack.py --config-file=./config/lrcn/config_lrcn_1.yaml
python adversarial_attack.py --config-file=./config/lrcn/config_lrcn_2.yaml
python adversarial_attack.py --config-file=./config/lrcn/config_lrcn_3.yaml
python adversarial_attack.py --config-file=./config/lrcn/config_lrcn_4.yaml
python adversarial_attack.py --config-file=./config/lrcn/config_lrcn_5.yaml
python adversarial_attack.py --config-file=./config/lrcn/config_lrcn_6.yaml
python adversarial_attack.py --config-file=./config/lrcn/config_lrcn_7.yaml
python adversarial_attack.py --config-file=./config/lrcn/config_lrcn_8.yaml
python adversarial_attack.py --config-file=./config/lrcn/config_lrcn_9.yaml
python adversarial_attack.py --config-file=./config/lrcn/config_lrcn_10.yaml
python adversarial_attack.py --config-file=./config/lrcn/config_lrcn_11.yaml
python adversarial_attack.py --config-file=./config/lrcn/config_lrcn_12.yaml